name = "Mallows"
uuid = "2bbb2f52-5e16-43fb-828b-f0eddea539fa"
authors = ["Luiz H N Lorena <luiz-lorena@hotmail.com> and contributors"]
version = "1.0.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.5"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
