name = "Mallows"
uuid = "2bbb2f52-5e16-43fb-828b-f0eddea539fa"
authors = ["Luiz H N Lorena <luiz-lorena@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
